apiVersion: v1
appVersion: 2.0.0
description: Helm chart for sidecar injector webhook deployment
engine: gotpl
keywords:
- cloudbees
- sidecar-injector
name: cloudbees-sidecar-injector
tillerVersion: '>=2.7.2'
version: 2.0.0
