apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata: 
  name: "docker-cache"
  namespace: "cloudbees"
spec: 
  accessModes: 
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Gi