apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: core.cb-gke.kearos.net
  namespace: cloudbees
spec:
  secretName: tls-core-cb-gke-kearos-net
  commonName: core.cb-gke.kearos.net
  dnsNames:
  - core.cb-gke.kearos.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - core.cb-gke.kearos.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer