apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: flow-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: flow-issuer-key
    solvers:
    - http01:
       ingress:
         class: flow-ingress